version: '2'

services:
  getir:
    image: 'getir-service:latest'
    build:
      context: .
    container_name: getir
    ports:
      - "8080:8080"
    expose:
      - "90"
    depends_on:
      - getirDB
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://getirDB:5432/getirDB
      - SPRING_DATASOURCE_USERNAME=getirDB
      - SPRING_DATASOURCE_PASSWORD=getirDB
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  getirDB:
    image: 'postgres:14.0-alpine'
    container_name: getirDB
    environment:
      - POSTGRES_USER=getirDB
      - POSTGRES_PASSWORD=getirDB
    ports:
      - "5435:5432"
    expose:
      - "5435"